apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: scalable-app
type: Opaque
data:
  host: <base64-encoded-db-host>
  port: <base64-encoded-db-port>
  name: <base64-encoded-db-name>
  username: <base64-encoded-db-username>
  password: <base64-encoded-db-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: scalable-app
type: Opaque
data:
  password: <base64-encoded-redis-password>
  url: <base64-encoded-redis-url>
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: scalable-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config>
