name: Simple Docker Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Docker Compose Setup
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test Docker Compose file syntax
      run: |
        # Validate docker-compose.yml syntax
        docker compose config

    - name: Build services (dry run)
      run: |
        # Test that we can build the images
        docker compose build --dry-run || docker compose config --quiet

    - name: Test individual Dockerfiles
      run: |
        # Test building individual services
        cd microservices/backend && docker build -f Dockerfile.simple -t test-backend .
        cd ../api-gateway && docker build -f Dockerfile.simple -t test-api-gateway .
        cd ../frontend && docker build -f Dockerfile.simple -t test-frontend .
        
        echo "✅ All individual Docker builds successful!"

    - name: Cleanup test images
      if: always()
      run: |
        docker rmi test-backend test-api-gateway test-frontend 2>/dev/null || true
        docker system prune -f
